# Default values for hop.
# This is a YAML-formatted file.

replicaCount: 1
hopLogLevel: "Basic"
hopProjectDirectory: "/files"
hopProjectName: "default"
hopEnvironmentName: "default-env"
hopEnvironmentConfigFileNamePaths: "/files/project-config.json"
hopServerUser: "admin"
hopServerPass: "admin"

image:
  repository: hop
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 8080

volumes:
  path: "/files"
  type: "Directory"

# Hop resources
resources:
  requests:
    memory: "1Gi"
    cpu: "1"